version: '3.8'

services:
    main:
      container_name: nestjs_api_main
      image: nestjs-api-main:1.0.0
      build:
          context: .
          target: development
          dockerfile: ./Dockerfile
      command: npm run start:debug
      ports:
          - 3000:3000
          - 9229:9229
      networks:
          - nesjs-network
      volumes:
          - .:/usr/src/app
          - /usr/src/app/node_modules
      restart: unless-stopped

networks:
    nesjs-network: